### ISSUE TITLE
node install fails to find script when `--experimental-modules` flag is enabled

### ISSUE THREAD

**Issue by bmacnaughton** [nodejs/modules#419]
`appoptics-bindings` has the npm install script `node setup-liboboe && node-gyp rebuild`. there is no `type` field in either `appoptics-bindings`' nor the test package's `package.json`.

when `--experimental-modules` is enabled node cannot find `setup-liboboe` and installation fails.

when `--experimental-modules` is NOT enabled node finds `setup-liboboe` and installation succeeds.

i am able to work around the problem by changing the install script to `node setup-liboboe.js`, i.e., adding the explicit extension.

the [docs](https://nodejs.org/docs/latest-v12.x/api/esm.html) (Enabling) don't specify that extension-based searching is turned off when the file would be interpreted as a cjs file. is that the case?

node v12.11.1 `NODE_OPTIONS=--experimental-modules`
npm 6.12.1
ubuntu 18.04

test package's package.json:
```
{
  "name": "esm-modules",
  "version": "1.0.0",
  "description": "testing 1, 2, 3...",
  "main": "main.mjs",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {},
  "devDependencies": {}
}
```

appoptics-bindings' package.json:
```
{
  "name": "appoptics-bindings",
  "version": "8.0.0",
  "description": "Bindings to liboboe for the AppOptics APM agent",
  "author": "Bruce A. MacNaughton <bruce@solarwinds.cloud>",
  "contributors": [
    "Stephen Belanger <admin@stephenbelanger.com>",
    "Silvio Fernandes <silviofernandes.developer@gmail.com"
  ],
  "main": "index.js",
  "gypfile": true,
  "license": {
    "name": "Librato Open License, Version 1.0",
    "url": "http://docs.traceview.solarwinds.com/Instrumentation/librato-open-license.html"
  },
  "repository": {
    "type": "git",
    "url": "https://github.com/appoptics/appoptics-bindings-node"
  },
  "bugs": {
    "url": "https://github.com/appoptics/appoptics-bindings-node/issues"
  },
  "scripts": {
    "test": "mocha test/*.test.js",
    "install": "node setup-liboboe && node-gyp rebuild",
    "rebuild": "node setup-liboboe && node-gyp rebuild"
  },
  "dependencies": {
    "bindings": "~1.2.1",
    "linux-os-info": "^2.0.0",
    "node-addon-api": "^1.6.3",
    "node-gyp": "^4.0.0"
  },
  "devDependencies": {
    "chai": "^4.2.0",
    "segfault-handler": "^1.2.0"
  }
}
```

execution log:

```
npm install ~/github.com/appoptics/ao-bindings/appoptics-bindings-8.0.0.tgz 
(node:21346) ExperimentalWarning: The ESM module loader is experimental.

> appoptics-bindings@8.0.0 install /home/bruce/working/esm-modules/node_modules/appoptics-bindings
> node setup-liboboe && node-gyp rebuild

(node:21368) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:79
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /home/bruce/working/esm-modules/node_modules/appoptics-bindings/setup-liboboe imported from /home/bruce/working/esm-modules/node_modules/appoptics-bindings/
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:79:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:152:40)
    at Loader.import (internal/modules/esm/loader.js:136:28)
    at internal/modules/cjs/loader.js:1004:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm WARN esm-modules@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appoptics-bindings@8.0.0 install: `node setup-liboboe && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appoptics-bindings@8.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruce/.npm/_logs/2019-11-01T15_00_07_034Z-debug.log

```

**Comment by guybedford** [comment]
Thanks for trying this out and reporting your issue here. Can you try with
the latest 12/13 versions? I believe this should work against the
compatibility PR that included fixes for cases like this.

**Comment by bmacnaughton** [comment]
thanks for the quick response.

i get the same error with node v12.13.0 but v13.0.1 works.
```
bruce@uxpanapa:~/working/esm-modules$ npm install ~/github.com/appoptics/ao-bindings/appoptics-bindings-8.0.0.tgz 
(node:24716) ExperimentalWarning: The ESM module loader is experimental.

> appoptics-bindings@8.0.0 install /home/bruce/working/esm-modules/node_modules/appoptics-bindings
> node setup-liboboe && node-gyp rebuild

(node:24728) ExperimentalWarning: The ESM module loader is experimental.
internal/modules/esm/default_resolve.js:82
  let url = moduleWrapResolve(specifier, parentURL);
            ^

Error: Cannot find module /home/bruce/working/esm-modules/node_modules/appoptics-bindings/setup-liboboe imported from /home/bruce/working/esm-modules/node_modules/appoptics-bindings/
    at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:82:13)
    at Loader.resolve (internal/modules/esm/loader.js:73:33)
    at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
    at Loader.import (internal/modules/esm/loader.js:131:28)
    at internal/modules/cjs/loader.js:1015:27
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_MODULE_NOT_FOUND'
}
npm WARN esm-modules@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appoptics-bindings@8.0.0 install: `node setup-liboboe && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appoptics-bindings@8.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruce/.npm/_logs/2019-11-01T15_36_32_118Z-debug.log
```
node 13.0.1 gets past this error but encounters #420
```
Now using node v13.0.1 (npm v6.12.0)
bruce@uxpanapa:~/working/esm-modules$ npm install ~/github.com/appoptics/ao-bindings/appoptics-bindings-8.0.0.tgz 
(node:26043) ExperimentalWarning: The ESM module loader is experimental.

> appoptics-bindings@8.0.0 install /home/bruce/working/esm-modules/node_modules/appoptics-bindings
> node setup-liboboe && node-gyp rebuild

(node:26058) ExperimentalWarning: The ESM module loader is experimental.
(node:26070) ExperimentalWarning: The ESM module loader is experimental.
(node:26086) ExperimentalWarning: The ESM module loader is experimental.
gyp: Call to 'node -p "require('node-addon-api').include"' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/bruce/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 4.15.0-66-generic
gyp ERR! command "/home/bruce/.nvm/versions/node/v13.0.1/bin/node" "/home/bruce/.nvm/versions/node/v13.0.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/bruce/working/esm-modules/node_modules/appoptics-bindings
gyp ERR! node -v v13.0.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN esm-modules@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! appoptics-bindings@8.0.0 install: `node setup-liboboe && node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the appoptics-bindings@8.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bruce/.npm/_logs/2019-11-01T15_37_44_877Z-debug.log
```
